// <auto-generated />
using System;
using FileArchive.FileService.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FileArchive.EFCore.Migrations.Migrations.File
{
    [DbContext(typeof(FileContext))]
    partial class FileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("FileArchive.FileService.FileArchiveInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Extension")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifyDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SubPath")
                        .HasColumnType("longtext");

                    b.Property<string>("UUId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FileArchiveInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
